# import = [
#   "~/.config/alacritty/catppuccin-mocha.toml"
# ]

[window]
padding = { x = 4, y = 4 }

[font]
size = 18.0

[font.bold]
style="Regular"
family = "Meslo LGM Nerd Font"

[font.italic]
family = "Meslo LGM Nerd Font"
style = "Italic"

[font.normal]
#family = "Meslo LGM Nerd Font"
family = "BitstromWera Nerd Font Propo"
style = "Regular"
