# import = [
#   "~/.config/alacritty/catppuccin-mocha.toml"
# ]

[font]
size = 18.0

[font.bold]
style="Regular"
family = "Meslo LGM Nerd Font"

[font.italic]
family = "Meslo LGM Nerd Font"
style = "Italic"

[font.normal]
family = "Meslo LGM Nerd Font"
style = "Regular"
