import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 18.0

[font.bold]
style="Regular"
family = "AnonymicePro Nerd Font"

[font.italic]
family = "AnonymicePro Nerd Font"
style = "Italic"

[font.normal]
family = "AnonymicePro Nerd Font"
style = "Regular"
